In [1]:
import numpy as np 
import pandas as pd

In [2]:
s = pd.Series([1,3,5, np.nan, 6, 8])

s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [5]:
dates = pd.date_range("20130101", periods=6)

dates 

df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list("ABCD"))
df


,A,B,C,D
2013-01-01,0.694149,0.277558,-1.622971,1.016996
2013-01-02,-0.729708,-1.136329,0.509865,1.844282
2013-01-03,1.105291,0.828767,0.098230,-1.716570
2013-01-04,1.741801,-0.931883,1.492771,0.397975
2013-01-05,0.176095,-2.725450,2.009585,0.474134
2013-01-06,0.448951,0.063204,0.242521,-0.273548


In [4]:
(np.random.randn(6,4))

array([[ 1.11995744,  0.44631051, -0.60380094, -0.70752679],
       [ 1.64177404, -0.67618062,  1.82074456, -0.95553649],
       [ 1.07393077,  1.20907397, -0.20871522,  0.94188164],
       [ 0.70861327, -0.25531736, -0.7458854 , -0.88446046],
       [ 0.22475131,  0.54299904,  1.61329575,  0.93350531],
       [-0.69114754,  1.48617695, -1.15542767, -1.34036191]])

In [14]:
df2 = pd.DataFrame({
    "A": 1.0,
    "B": pd.Timestamp("20130102"),
    "C": pd.Series(1, index=list(range(5)), dtype="float32"), 
    "D": np.array([6] * 5, dtype="int32"),
    "E": pd.Categorical(["test", "test", "test", "train", "train"]),
    "F": "foo"
})

df2

,A,B,C,D,E,F
0,1.0,2013-01-02,1.0,6,test,foo
1,1.0,2013-01-02,1.0,6,test,foo
2,1.0,2013-01-02,1.0,6,test,foo
3,1.0,2013-01-02,1.0,6,train,foo
4,1.0,2013-01-02,1.0,6,train,foo


In [18]:
df2.dtypes


A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [23]:
df.head()

df.tail(2)


,A,B,C,D
2013-01-05,0.176095,-2.725450,2.009585,0.474134
2013-01-06,0.448951,0.063204,0.242521,-0.273548


In [28]:
df.index
df.columns
df

,A,B,C,D
2013-01-01,0.694149,0.277558,-1.622971,1.016996
2013-01-02,-0.729708,-1.136329,0.509865,1.844282
2013-01-03,1.105291,0.828767,0.098230,-1.716570
2013-01-04,1.741801,-0.931883,1.492771,0.397975
2013-01-05,0.176095,-2.725450,2.009585,0.474134
2013-01-06,0.448951,0.063204,0.242521,-0.273548


In [32]:
df[df.index == '2013-01-02']

,A,B,C,D
2013-01-02,-0.729708,-1.136329,0.509865,1.844282


In [33]:
df.to_numpy()

array([[ 0.6941491 ,  0.27755767, -1.62297075,  1.0169957 ],
       [-0.72970831, -1.13632858,  0.50986529,  1.84428202],
       [ 1.10529127,  0.82876734,  0.09822986, -1.7165698 ],
       [ 1.74180087, -0.93188322,  1.4927708 ,  0.39797487],
       [ 0.17609516, -2.72544992,  2.00958494,  0.4741337 ],
       [ 0.44895085,  0.0632044 ,  0.24252124, -0.27354751]])

In [35]:
df2.dtypes 

df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 6, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 6, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 6, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 6, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 6, 'train', 'foo']],
      dtype=object)

In [36]:
df.describe()

,A,B,C,D
count,6.000000,6.000000,6.000000,6.000000
mean,0.572763,-0.604022,0.455000,0.290545
std,0.840723,1.278011,1.263891,1.211097
min,-0.729708,-2.725450,-1.622971,-1.716570
25%,0.244309,-1.085217,0.134303,-0.105667
50%,0.571550,-0.434339,0.376193,0.436054
75%,1.002506,0.223969,1.247044,0.881280
max,1.741801,0.828767,2.009585,1.844282


In [40]:
df.T

,2013-01-01,2013-01-02,2013-01-03,2013-01-04,2013-01-05,2013-01-06
A,0.694149,-0.729708,1.105291,1.741801,0.176095,0.448951
B,0.277558,-1.136329,0.828767,-0.931883,-2.725450,0.063204
C,-1.622971,0.509865,0.098230,1.492771,2.009585,0.242521
D,1.016996,1.844282,-1.716570,0.397975,0.474134,-0.273548


In [50]:
df.sort_index(axis=0, ascending=True)

,A,B,C,D
2013-01-01,0.694149,0.277558,-1.622971,1.016996
2013-01-02,-0.729708,-1.136329,0.509865,1.844282
2013-01-03,1.105291,0.828767,0.098230,-1.716570
2013-01-04,1.741801,-0.931883,1.492771,0.397975
2013-01-05,0.176095,-2.725450,2.009585,0.474134
2013-01-06,0.448951,0.063204,0.242521,-0.273548


In [55]:
df.sort_values(by="B", ascending=True)
df

,A,B,C,D
2013-01-01,0.694149,0.277558,-1.622971,1.016996
2013-01-02,-0.729708,-1.136329,0.509865,1.844282
2013-01-03,1.105291,0.828767,0.098230,-1.716570
2013-01-04,1.741801,-0.931883,1.492771,0.397975
2013-01-05,0.176095,-2.725450,2.009585,0.474134
2013-01-06,0.448951,0.063204,0.242521,-0.273548


In [54]:
df.A

2013-01-01    0.694149
2013-01-02   -0.729708
2013-01-03    1.105291
2013-01-04    1.741801
2013-01-05    0.176095
2013-01-06    0.448951
Freq: D, Name: A, dtype: float64

In [57]:
df[0:5]

,A,B,C,D
2013-01-01,0.694149,0.277558,-1.622971,1.016996
2013-01-02,-0.729708,-1.136329,0.509865,1.844282
2013-01-03,1.105291,0.828767,0.098230,-1.716570
2013-01-04,1.741801,-0.931883,1.492771,0.397975
2013-01-05,0.176095,-2.725450,2.009585,0.474134


In [61]:
df.loc[dates[1]]



A   -0.729708
B   -1.136329
C    0.509865
D    1.844282
Name: 2013-01-02 00:00:00, dtype: float64

In [ ]:
df.loc[:, ["A", "B"]]

Why is first using index or rows to find the date and the second is working with columns. Pandas is using row based so label based and it works with row first column second

In [65]:
df.loc[[dates[0], dates[1]], "A": "C"]

,A,B,C
2013-01-01,0.694149,0.277558,-1.622971
2013-01-02,-0.729708,-1.136329,0.509865


In [64]:
df.loc["20130102": "20130104", "A":"C"]

,A,B,C
2013-01-02,-0.729708,-1.136329,0.509865
2013-01-03,1.105291,0.828767,0.098230
2013-01-04,1.741801,-0.931883,1.492771


Use square brackets if we want to select a listing of 1,2,3,4 of items. No square brackets if we want to slice the data 

In [66]:
df.at[dates[0], "A"]

np.float64(0.6941490992339152)

In [69]:
s = pd.Series([1, 2, 3, 4])

result = s + 5
s
result

0    6
1    7
2    8
3    9
dtype: int64

In [71]:
df

,A,B,C,D
2013-01-01,0.694149,0.277558,-1.622971,1.016996
2013-01-02,-0.729708,-1.136329,0.509865,1.844282
2013-01-03,1.105291,0.828767,0.098230,-1.716570
2013-01-04,1.741801,-0.931883,1.492771,0.397975
2013-01-05,0.176095,-2.725450,2.009585,0.474134
2013-01-06,0.448951,0.063204,0.242521,-0.273548


In [78]:
df.iloc[2:5, 0:2]


,A,B
2013-01-03,1.105291,0.828767
2013-01-04,1.741801,-0.931883
2013-01-05,0.176095,-2.725450


In [79]:
df.iloc[1:3, :]

,A,B,C,D
2013-01-02,-0.729708,-1.136329,0.509865,1.844282
2013-01-03,1.105291,0.828767,0.098230,-1.716570


In [80]:
df.iloc[:, 1:3]

,B,C
2013-01-01,0.277558,-1.622971
2013-01-02,-1.136329,0.509865
2013-01-03,0.828767,0.098230
2013-01-04,-0.931883,1.492771
2013-01-05,-2.725450,2.009585
2013-01-06,0.063204,0.242521


In [81]:
df.iloc[1,2]

np.float64(0.5098652940099118)

In [82]:
df.iat[1,2]

np.float64(0.5098652940099118)

iat is used for a single position. more performant 

Boolean indexing 
Select rows where df.A is greater than 1

In [84]:
df[df["A"] > 1]

,A,B,C,D
2013-01-03,1.105291,0.828767,0.098230,-1.716570
2013-01-04,1.741801,-0.931883,1.492771,0.397975


In [85]:
df[df > 1]

,A,B,C,D
2013-01-01,NaN,NaN,NaN,1.016996
2013-01-02,NaN,NaN,NaN,1.844282
2013-01-03,1.105291,NaN,NaN,NaN
2013-01-04,1.741801,NaN,1.492771,NaN
2013-01-05,NaN,NaN,2.009585,NaN
2013-01-06,NaN,NaN,NaN,NaN


In [ ]:
df2 = df.copy()
df2["E"] = ["one", "two", "three", "four", "three", "five"]
df2



,A,B,C,D,E
2013-01-01,0.694149,0.277558,-1.622971,1.016996,one
2013-01-02,-0.729708,-1.136329,0.509865,1.844282,two
2013-01-03,1.105291,0.828767,0.098230,-1.716570,three
2013-01-04,1.741801,-0.931883,1.492771,0.397975,four
2013-01-05,0.176095,-2.725450,2.009585,0.474134,three
2013-01-06,0.448951,0.063204,0.242521,-0.273548,five


In [90]:
df2[df2["E"].isin(["two", "four"])]


,A,B,C,D,E
2013-01-02,-0.729708,-1.136329,0.509865,1.844282,two
2013-01-04,1.741801,-0.931883,1.492771,0.397975,four


Setting 
setting a new column automatically aligns the data by indexes 

In [93]:
s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range("20130102", periods=6))
s1
df["F"] = s1
df

,A,B,C,D,F
2013-01-01,0.694149,0.277558,-1.622971,1.016996,NaN
2013-01-02,-0.729708,-1.136329,0.509865,1.844282,1.0
2013-01-03,1.105291,0.828767,0.098230,-1.716570,2.0
2013-01-04,1.741801,-0.931883,1.492771,0.397975,3.0
2013-01-05,0.176095,-2.725450,2.009585,0.474134,4.0
2013-01-06,0.448951,0.063204,0.242521,-0.273548,5.0


In [95]:
df.at[dates[0], "A"] = 0
df

,A,B,C,D,F
2013-01-01,0.000000,0.277558,-1.622971,1.016996,NaN
2013-01-02,-0.729708,-1.136329,0.509865,1.844282,1.0
2013-01-03,1.105291,0.828767,0.098230,-1.716570,2.0
2013-01-04,1.741801,-0.931883,1.492771,0.397975,3.0
2013-01-05,0.176095,-2.725450,2.009585,0.474134,4.0
2013-01-06,0.448951,0.063204,0.242521,-0.273548,5.0


In [97]:
df.loc[:, "D"] = np.array([5] * len(df))
df

,A,B,C,D,F
2013-01-01,0.000000,0.277558,-1.622971,5.0,NaN
2013-01-02,-0.729708,-1.136329,0.509865,5.0,1.0
2013-01-03,1.105291,0.828767,0.098230,5.0,2.0
2013-01-04,1.741801,-0.931883,1.492771,5.0,3.0
2013-01-05,0.176095,-2.725450,2.009585,5.0,4.0
2013-01-06,0.448951,0.063204,0.242521,5.0,5.0


In [98]:
df2 = df.copy()
df2[df2 > 0] = -df2

df2

,A,B,C,D,F
2013-01-01,0.000000,-0.277558,-1.622971,-5.0,NaN
2013-01-02,-0.729708,-1.136329,-0.509865,-5.0,-1.0
2013-01-03,-1.105291,-0.828767,-0.098230,-5.0,-2.0
2013-01-04,-1.741801,-0.931883,-1.492771,-5.0,-3.0
2013-01-05,-0.176095,-2.725450,-2.009585,-5.0,-4.0
2013-01-06,-0.448951,-0.063204,-0.242521,-5.0,-5.0


In [99]:
df2

,A,B,C,D,F
2013-01-01,0.000000,-0.277558,-1.622971,-5.0,NaN
2013-01-02,-0.729708,-1.136329,-0.509865,-5.0,-1.0
2013-01-03,-1.105291,-0.828767,-0.098230,-5.0,-2.0
2013-01-04,-1.741801,-0.931883,-1.492771,-5.0,-3.0
2013-01-05,-0.176095,-2.725450,-2.009585,-5.0,-4.0
2013-01-06,-0.448951,-0.063204,-0.242521,-5.0,-5.0


Missing data 
for numpy data types np.nan represents missing data. It is default not included in computations 

In [111]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ["E"])
df1

df1.loc[dates[0]: dates[1], "E"] = 1
df1
df1.drop(columns=["E"])
df1.loc[dates[0]: dates[1], "E"] = 1
df1

,A,B,C,D,F,E,E
2013-01-01,0.000000,0.277558,-1.622971,5.0,NaN,1.0,1.0
2013-01-02,-0.729708,-1.136329,0.509865,5.0,1.0,1.0,1.0
2013-01-03,1.105291,0.828767,0.098230,5.0,2.0,NaN,NaN
2013-01-04,1.741801,-0.931883,1.492771,5.0,3.0,NaN,NaN


In [109]:
df1.dropna(how="any")

,A,B,C,D,F,E,E
2013-01-02,-0.729708,-1.136329,0.509865,5.0,1.0,1.0,1.0


In [112]:
df1.fillna(value=3)

,A,B,C,D,F,E,E
2013-01-01,0.000000,0.277558,-1.622971,5.0,3.0,1.0,1.0
2013-01-02,-0.729708,-1.136329,0.509865,5.0,1.0,1.0,1.0
2013-01-03,1.105291,0.828767,0.098230,5.0,2.0,3.0,3.0
2013-01-04,1.741801,-0.931883,1.492771,5.0,3.0,3.0,3.0


In [113]:
df

,A,B,C,D,F,E
2013-01-01,0.000000,0.277558,-1.622971,5.0,NaN,1.0
2013-01-02,-0.729708,-1.136329,0.509865,5.0,1.0,1.0
2013-01-03,1.105291,0.828767,0.098230,5.0,2.0,NaN
2013-01-04,1.741801,-0.931883,1.492771,5.0,3.0,NaN
2013-01-05,0.176095,-2.725450,2.009585,5.0,4.0,NaN
2013-01-06,0.448951,0.063204,0.242521,5.0,5.0,NaN


In [114]:
df.mean()

A    0.457072
B   -0.604022
C    0.455000
D    5.000000
F    3.000000
E    1.000000
dtype: float64

In [115]:
df.mean(axis=1)

2013-01-01    0.930917
2013-01-02    0.940638
2013-01-03    1.806458
2013-01-04    2.060538
2013-01-05    1.692046
2013-01-06    2.150935
Freq: D, dtype: float64

In [117]:
df

,A,B,C,D,F,E
2013-01-01,0.000000,0.277558,-1.622971,5.0,NaN,1.0
2013-01-02,-0.729708,-1.136329,0.509865,5.0,1.0,1.0
2013-01-03,1.105291,0.828767,0.098230,5.0,2.0,NaN
2013-01-04,1.741801,-0.931883,1.492771,5.0,3.0,NaN
2013-01-05,0.176095,-2.725450,2.009585,5.0,4.0,NaN
2013-01-06,0.448951,0.063204,0.242521,5.0,5.0,NaN


In [120]:
df.dropna()
row_means = df.sum(axis=1) / df.shape[1]
row_means

2013-01-01    0.775764
2013-01-02    0.940638
2013-01-03    1.505381
2013-01-04    1.717115
2013-01-05    1.410038
2013-01-06    1.792446
Freq: D, dtype: float64

In [125]:
row_means = df.sum(axis=0) / df.count(axis=0)
row_means
df

,A,B,C,D,F,E
2013-01-01,0.000000,0.277558,-1.622971,5.0,NaN,1.0
2013-01-02,-0.729708,-1.136329,0.509865,5.0,1.0,1.0
2013-01-03,1.105291,0.828767,0.098230,5.0,2.0,NaN
2013-01-04,1.741801,-0.931883,1.492771,5.0,3.0,NaN
2013-01-05,0.176095,-2.725450,2.009585,5.0,4.0,NaN
2013-01-06,0.448951,0.063204,0.242521,5.0,5.0,NaN


Why am I getting different sums. Auto ignoring nan 

In [128]:
s = pd.Series([1, 3, 5, np.nan, 6, 8], index=dates)
s

2013-01-01    1.0
2013-01-02    3.0
2013-01-03    5.0
2013-01-04    NaN
2013-01-05    6.0
2013-01-06    8.0
Freq: D, dtype: float64

In [130]:
df

,A,B,C,D,F,E
2013-01-01,0.000000,0.277558,-1.622971,5.0,NaN,1.0
2013-01-02,-0.729708,-1.136329,0.509865,5.0,1.0,1.0
2013-01-03,1.105291,0.828767,0.098230,5.0,2.0,NaN
2013-01-04,1.741801,-0.931883,1.492771,5.0,3.0,NaN
2013-01-05,0.176095,-2.725450,2.009585,5.0,4.0,NaN
2013-01-06,0.448951,0.063204,0.242521,5.0,5.0,NaN


In [131]:
# df.agg(lambda x: np.mean(x) * 5.6)

df.transform(lambda x: x + 1)

,A,B,C,D,F,E
2013-01-01,1.000000,1.277558,-0.622971,6.0,NaN,2.0
2013-01-02,0.270292,-0.136329,1.509865,6.0,2.0,2.0
2013-01-03,2.105291,1.828767,1.098230,6.0,3.0,NaN
2013-01-04,2.741801,0.068117,2.492771,6.0,4.0,NaN
2013-01-05,1.176095,-1.725450,3.009585,6.0,5.0,NaN
2013-01-06,1.448951,1.063204,1.242521,6.0,6.0,NaN


In [133]:
s = pd.Series(np.random.randint(0, 7, size=10))
s

s.value_counts()

2    3
0    3
5    2
3    1
6    1
Name: count, dtype: int64

In [134]:
s = pd.Series(["A", "B", "C", "Aaba", "Baca", np.nan, "CABA", "dog", "cat"])

s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

In [137]:
df = pd.DataFrame(np.random.randn(10, 4))
df

pieces = [df[:3], df[3:7], df[7:]]
pieces 

[          0         1         2         3
 0  0.774475 -1.687874 -0.131361  0.599282
 1 -0.999813  0.342642  1.181544  1.436507
 2  0.675606  0.113339  0.232433  1.243348,
           0         1         2         3
 3  1.132472  0.175171 -0.739922  0.212323
 4  0.339154 -0.620799  0.793427 -0.675824
 5  0.886662 -1.604024  0.673930  0.020020
 6  0.696560 -0.819954  0.407971 -1.872166,
           0         1         2         3
 7 -0.812712  0.277936  0.594093 -0.436730
 8 -0.335898 -0.900710 -0.173937 -1.767385
 9  0.869091 -0.652255 -0.281934 -0.434788]

In [138]:
pd.concat(pieces)

,0,1,2,3
0,0.774475,-1.687874,-0.131361,0.599282
1,-0.999813,0.342642,1.181544,1.436507
2,0.675606,0.113339,0.232433,1.243348
3,1.132472,0.175171,-0.739922,0.212323
4,0.339154,-0.620799,0.793427,-0.675824
5,0.886662,-1.604024,0.673930,0.020020
6,0.696560,-0.819954,0.407971,-1.872166
7,-0.812712,0.277936,0.594093,-0.436730
8,-0.335898,-0.900710,-0.173937,-1.767385
9,0.869091,-0.652255,-0.281934,-0.434788


In [139]:
left = pd.DataFrame({"key": ["foo", "foo"], "lval": [1, 2]})
left

,key,lval
0,foo,1
1,foo,2


In [140]:
right = pd.DataFrame({"key": ["foo", "foo"], "rval": [4, 5]}) 
right


,key,rval
0,foo,4
1,foo,5


In [141]:
pd.merge(left, right, on="key")

,key,lval,rval
0,foo,1,4
1,foo,1,5
2,foo,2,4
3,foo,2,5
